### ISSUE TITLE
Intermittent unit test failure in multiRouteAABBAB test.

### ISSUE THREAD

**Issue by holidaymike** [xmidt-org/ears#124]
The unit tests pass most of the time, but occasionally, we will see the following error:
handlers_v1_test.go:296: multiRouteAABBAB test: check events sent error: unexpected number of events in sender 8 (10)

The error is intermittent, and there is currently no known way to reliably reproduce the issue. In github, it often happens at the first go test run after significant code changes. Locally, it also happens if there are significant code changes sync down from github.

**Comment by boriwo** [comment]
see https://github.com/xmidt-org/ears/issues/168
