### ISSUE TITLE
Trace ID mismatch in logging and tracing in EARS API

### ISSUE THREAD

**Issue by holidaymike** [xmidt-org/ears#152]
When using EARS API, we will generate traceIds for logging and tracing. However, they are different with no correlation. We should consolidate them into a single trace id.

**Comment by gtrevg** [comment]
@holidaymike For reference, the key in the log should be `trace.id`.  This is based off of the Elastic Common Schema recommendation:

* https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html
